version: '3'

services:
  logger:
    image: logger 
    build:
      context: ./Logger
      dockerfile: Dockerfile
    container_name: logger
    environment:
      - "RABBITMQ_HOST=rabbit"
      - "RABBITMQ_PORT=5672"
      - "RABBITMQ_USER=guest"
      - "RABBITMQ_PASS=guest"
    depends_on:
      - rabbit

  hotelbookingservice:
    image: hotelbookingservice 
    build:
      context: ./HotelBookingService
      dockerfile: Dockerfile
    container_name: hotelbookingservice
    environment:
      - "RABBITMQ_HOST=rabbit"
      - "RABBITMQ_PORT=5672"
      - "RABBITMQ_USER=guest"
      - "RABBITMQ_PASS=guest"
    depends_on:
      - rabbit
      - mssql

  externalservice:
    image: externalservice
    build:
      context: ./ExternalService
      dockerfile: Dockerfile
    container_name: externalservice
    ports:
      - "8080:44311"
    environment:
      - "RABBITMQ_HOST=rabbit"
      - "RABBITMQ_PORT=5672"
      - "RABBITMQ_USER=guest"
      - "RABBITMQ_PASS=guest"
    depends_on:
      - rabbit

  externalservice-node:
    image: externalservicenode
    build:
      context: ./external-service-node
      dockerfile: Dockerfile
    container_name: externalservicenode
    ports:
      - "8079:3001"
    environment:
      - "RABBITMQ_HOST=rabbit"
      - "RABBITMQ_PORT=5672"
      - "RABBITMQ_USER=guest"
      - "RABBITMQ_PASS=guest"
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq:3.7.2-management
    hostname: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - ~apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=yourStrong(!)Password"
      - "MSSQL_HOST=mssql"
      - "MSSQL_PORT=1433"